
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t roof_image .

test-job:
  stage: test
  script:
    - docker run --rm roof_image -d

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
