
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t roof_image .

test-job:
  stage: test
  script:
    - docker run --rm -d roof_image

deploy-job:
  stage: deploy
  before_script:
  - echo "$ENV_FILE_CONTENT" > .env
  script:
    - docker compose up -d
