stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - unset DOCKER_HOST
    - docker build -t roof_image .
  only:
    - main

test-job:
  stage: test
  script:
    - docker run --rm -d roof_image
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - main
