stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY/namespace/project/roof_image:latest"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose
  - docker info
  - echo "Docker and Compose are ready."

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker compose up -d --build
  only:
    - main