stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY/namespace/project/roof_image:latest"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apt-get update && apt-get install -y docker-compose-plugin
  - docker info

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  only:
    - main

test-job:
  stage: test
  script:
    - docker run --name test_container -d "$IMAGE_NAME"
    - sleep 5
    - docker ps -a
    - docker logs test_container
    - docker rm -f test_container
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - main