
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t roof_image .

test-job:
  stage: test
  script:
    - docker run --rm -d roof_image

deploy-job:
  stage: deploy
  before_script:
  - echo "$ENV_FILE_CONTENT" > .env
  - if [ -f .env ]; then echo ".env file created successfully"; else echo ".env file creation failed" && exit 1; fi
  script:
    - docker compose up -d
