stages:
  - build
  - test
  - deploy

build:
  image: docker
  services:
    - name: docker:dind
      alias: docker
  stage: build
  script:
    - docker build -t roof_image .
  only:
    - main

test-job:
  stage: test
  script:
    - docker run --rm -d roof_image
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - main
