stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t roof_image .
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - main
