services:
  db:
    image: postgres:15
    container_name: roof_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: roof_redis

  roof_app:
    image: roof_image
    build:
      context: .
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    container_name: roof_app
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started
      # grafana:
      #   condition: service_started
      # prometheus:
      #   condition: service_started
    command: ['/auto_app/docker/app.sh']
    ports:
      - 8000:8000
  # roof_app_dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: roof_app_dev
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app # 💡 для live reload
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #     - redis

  # prometheus:
  #   image: prom/prometheus:v2.43.0
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   restart: unless-stopped
  #   ports:
  #     - 9090:9090

  # grafana:
  #   image: grafana/grafana:9.4.7
  #   container_name: grafana
  #   volumes:
  #     - grafanadata:/var/lib/grafana
  #   # depends_on:
  #   #   - prometheus
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000

volumes:
  postgresdata:
  # grafanadata:
  # prometheusdata:
