services:
  db:
    image: postgres:15
    container_name: roof_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5433:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: roof_redis

  migrate:
    build:
      context: .
    container_name: roof_migrate
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ['/auto_app/docker/migrate.sh']

  roof_app:
    build:
      context: .
    container_name: roof_app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: ['/auto_app/docker/app.sh']
    ports:
      - "8001:8001"

volumes:
  postgresdata: