"""Auto migration

Revision ID: 4bf2b0d4637b
Revises: 9d9c0c35308e
Create Date: 2025-05-18 11:47:17.956902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf2b0d4637b'
down_revision: Union[str, None] = '9d9c0c35308e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('type', sa.String(), nullable=False))
    op.add_column('tariff', sa.Column('price_sale', sa.Integer(), nullable=False))
    op.add_column('tariff', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('tariff', sa.Column('atributes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff', 'atributes')
    op.drop_column('tariff', 'duration')
    op.drop_column('tariff', 'price_sale')
    op.drop_column('tariff', 'type')
    # ### end Alembic commands ###
