"""Auto migration

Revision ID: 7402b1fa9269
Revises: b36b40fe4fe7
Create Date: 2025-05-20 10:13:54.784259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7402b1fa9269'
down_revision: Union[str, None] = 'b36b40fe4fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('name_device', sa.String(), nullable=False))
    op.add_column('sessions', sa.Column('city', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'city')
    op.drop_column('sessions', 'name_device')
    # ### end Alembic commands ###
