"""Auto migration

Revision ID: 9d9c0c35308e
Revises: 5e44d15a1934
Create Date: 2025-05-17 16:51:31.154794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9c0c35308e'
down_revision: Union[str, None] = '5e44d15a1934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('OGRN', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'OGRN')
    # ### end Alembic commands ###
